"use client";

import { useState } from "react";
import { exportToPDF, PRINT_CSS } from "@/lib/exportToPDF";

// ── Section definitions ───────────────────────────────────────────────────────

const SECTIONS = [
  { key: "companyOverview",             label: "Company Overview",               icon: "🏢", num: 1,  color: "#f59e0b" },
  { key: "founderAdvantage",            label: "Founder Advantage",              icon: "👤", num: 2,  color: "#f472b6" },
  { key: "companyAdvantages",           label: "Company Advantages",             icon: "⚡", num: 3,  color: "#a78bfa" },
  { key: "industryOverview",            label: "Industry Overview",              icon: "🌐", num: 4,  color: "#60a5fa" },
  { key: "marketResearch",              label: "Market Research",                icon: "📊", num: 5,  color: "#34d399" },
  { key: "marketGapOpportunity",        label: "Market Gap & Opportunity",       icon: "🎯", num: 6,  color: "#fb923c" },
  { key: "targetCustomers",             label: "Target Customers",               icon: "👥", num: 7,  color: "#00d4ff" },
  { key: "productsServices",            label: "Products and Services",          icon: "📦", num: 8,  color: "#4ade80" },
  { key: "operatingModel",              label: "Operating Model",                icon: "⚙️", num: 9,  color: "#94a3b8" },
  { key: "strategicPositioning",        label: "Strategic Positioning",          icon: "♟️", num: 10, color: "#fbbf24" },
  { key: "dataInfrastructureAdvantage", label: "Data Infrastructure Advantage",  icon: "🔧", num: 11, color: "#22d3ee" },
  { key: "growthStrategy",              label: "Growth Strategy",                icon: "📈", num: 12, color: "#86efac" },
  { key: "threeYearGrowthVision",       label: "Three-Year Growth Vision",       icon: "🔭", num: 13, color: "#f472b6" },
  { key: "financialOverviewBudget",     label: "Financial Overview & Budget",    icon: "💰", num: 14, color: "#fbbf24" },
  { key: "revenueModel",                label: "Revenue Model",                  icon: "💳", num: 15, color: "#34d399" },
  { key: "fundingRequestCapital",       label: "Funding Request & Use of Capital", icon: "🏦", num: 16, color: "#818cf8" },
  { key: "vision",                      label: "Vision",                         icon: "✨", num: 17, color: "#f9a8d4" },
  { key: "summary",                     label: "Summary",                        icon: "📋", num: 18, color: "#f59e0b" },
];

// ── Export helpers ────────────────────────────────────────────────────────────

function buildPlainText(plan, companyName) {
  const lines = [
    `BUSINESS PLAN — ${(companyName || "").toUpperCase()}`,
    "═══════════════════════════════════════════════════════",
    "",
    "Generated by NAVI | Springer Industries Professional Framework",
    "",
  ];
  SECTIONS.forEach(({ num, label, key }) => {
    lines.push(`${num}. ${label.toUpperCase()}`);
    lines.push("────────────────────────────────────────────────────");
    lines.push(plan[key] || "");
    lines.push("");
  });
  lines.push("═══════════════════════════════════════════════════════");
  lines.push("Professional Business Plan — NAVI by Springer Industries");
  return lines.join("\n");
}

function buildHTML(plan, companyName) {
  const sectionHtml = SECTIONS.map(({ num, label, key }) => {
    const content = (plan[key] || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    return `<div class="section">
  <div class="section-title">${num}. ${label}</div>
  <p>${content}</p>
</div>`;
  }).join("\n\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${companyName || "Business Plan"} — Business Plan</title>
  <style>
${PRINT_CSS}
  </style>
</head>
<body>
  <div class="section" style="border-bottom:2px solid #111;padding-bottom:16px;margin-bottom:32px;">
    <h1>${(companyName || "Business Plan").replace(/&/g, "&amp;").replace(/</g, "&lt;")}</h1>
    <div style="font-size:11px;color:#888;letter-spacing:1.5px;text-transform:uppercase;margin-top:6px;">
      Professional Business Plan · Springer Industries Framework
    </div>
  </div>

${sectionHtml}

  <div class="footer">
    Generated by NAVI · Springer Industries · ${new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" })}
  </div>
</body>
</html>`;
}

// ── Section card ──────────────────────────────────────────────────────────────

function SectionCard({ num, icon, label, color, children }) {
  return (
    <div
      className="rounded-xl overflow-hidden"
      style={{
        background: "rgba(255,255,255,0.025)",
        border:     `1px solid rgba(255,255,255,0.06)`,
      }}
    >
      {/* Section header */}
      <div
        className="px-4 py-2.5 flex items-center gap-2.5"
        style={{
          borderBottom: `1px solid rgba(255,255,255,0.05)`,
          background:   `rgba(${hexToRgb(color)},0.05)`,
        }}
      >
        <span
          className="flex-shrink-0 w-5 h-5 rounded-full flex items-center justify-center text-[9px] font-mono font-bold"
          style={{
            background: `rgba(${hexToRgb(color)},0.15)`,
            border:     `1px solid rgba(${hexToRgb(color)},0.35)`,
            color,
          }}
        >
          {num}
        </span>
        <span style={{ fontSize: 10 }}>{icon}</span>
        <span
          className="text-[9px] font-mono tracking-[0.2em] uppercase font-bold flex-1"
          style={{ color }}
        >
          {label}
        </span>
      </div>

      {/* Content */}
      <div className="px-4 py-3">
        {children}
      </div>
    </div>
  );
}

// Helper: convert 6-digit hex colour to "R,G,B" for rgba()
function hexToRgb(hex) {
  const c = hex.replace("#", "");
  const r = parseInt(c.substring(0, 2), 16);
  const g = parseInt(c.substring(2, 4), 16);
  const b = parseInt(c.substring(4, 6), 16);
  return `${r},${g},${b}`;
}

// ── Main component ────────────────────────────────────────────────────────────

export default function BusinessPlanCard({
  plan,
  companyName,
  emailSent,
  userEmail,
  onRestart,
  onClose,
}) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    const text = buildPlainText(plan, companyName);
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      const el = document.createElement("textarea");
      el.value = text;
      document.body.appendChild(el);
      el.select();
      document.execCommand("copy");
      document.body.removeChild(el);
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 2200);
  };

  const handleDownloadPDF = () => {
    exportToPDF(buildHTML(plan, companyName));
  };

  return (
    <div className="flex flex-col gap-4">
      {/* Success header */}
      <div className="flex flex-col items-center gap-1.5 py-3 text-center">
        <span style={{ fontSize: 30 }}>🚀</span>
        <span className="text-sm font-mono font-bold text-white">
          {companyName ? `${companyName} — Business Plan` : "Your Business Plan is Ready"}
        </span>
        <span className="text-xs font-mono text-slate-500">
          Professional · Springer Industries Framework · 18 Sections
        </span>
      </div>

      {/* Email confirmation badge */}
      {(emailSent || userEmail) && (
        <div
          className="flex items-center gap-2 px-3 py-2 rounded-xl"
          style={{
            background: emailSent
              ? "rgba(74,222,128,0.07)"
              : "rgba(255,255,255,0.04)",
            border: emailSent
              ? "1px solid rgba(74,222,128,0.25)"
              : "1px solid rgba(255,255,255,0.07)",
          }}
        >
          <span style={{ fontSize: 12 }}>{emailSent ? "✅" : "📧"}</span>
          <span
            className="text-[10px] font-mono"
            style={{ color: emailSent ? "#86efac" : "#475569" }}
          >
            {emailSent
              ? `Plan sent${userEmail ? ` to ${userEmail}` : " to your email"}`
              : "Email delivery pending — check your inbox shortly"}
          </span>
        </div>
      )}

      {/* 18-section plan */}
      <div className="flex flex-col gap-3">
        {SECTIONS.map(({ key, num, icon, label, color }) => (
          <SectionCard key={key} num={num} icon={icon} label={label} color={color}>
            <p className="text-xs font-mono text-slate-300 leading-relaxed">
              {plan[key] || <span className="text-slate-600 italic">Not generated</span>}
            </p>
          </SectionCard>
        ))}
      </div>

      {/* Action buttons */}
      <div className="flex gap-3 pt-1">
        <button
          onClick={handleCopy}
          className="flex-1 flex items-center justify-center gap-2 py-3 rounded-xl font-mono text-sm font-bold transition-all duration-200"
          style={{
            background: copied ? "rgba(74,222,128,0.12)" : "rgba(255,255,255,0.05)",
            border:     copied ? "1px solid rgba(74,222,128,0.4)" : "1px solid rgba(255,255,255,0.1)",
            color:      copied ? "#4ade80" : "#94a3b8",
          }}
        >
          {copied ? "✓ Copied!" : "📋 Copy Plan"}
        </button>
        <button
          onClick={handleDownloadPDF}
          className="flex-1 flex items-center justify-center gap-2 py-3 rounded-xl font-mono text-sm font-bold transition-all duration-200"
          style={{
            background: "rgba(245,158,11,0.1)",
            border:     "1px solid rgba(245,158,11,0.35)",
            color:      "#f59e0b",
            boxShadow:  "0 0 10px rgba(245,158,11,0.1)",
          }}
        >
          📥 Download PDF
        </button>
      </div>

      {/* Secondary actions */}
      <div className="flex gap-3 pb-4">
        <button
          onClick={onRestart}
          className="flex-1 py-2 rounded-xl font-mono text-xs transition-all duration-200"
          style={{
            border: "1px solid rgba(255,255,255,0.07)",
            color:  "rgba(100,116,139,0.8)",
          }}
        >
          ↺ Start Over
        </button>
        <button
          onClick={onClose}
          className="flex-1 py-2 rounded-xl font-mono text-xs transition-all duration-200"
          style={{
            border: "1px solid rgba(255,255,255,0.07)",
            color:  "rgba(100,116,139,0.8)",
          }}
        >
          ✕ Close
        </button>
      </div>
    </div>
  );
}
