export default function TermsOfUse() {
  return (
    <div style={{
      minHeight: "100dvh",
      background: "#08080f",
      color: "#e2e8f0",
      fontFamily: "'Courier New', Courier, monospace",
      padding: "0 0 60px",
    }}>
      {/* Header */}
      <div style={{
        position: "sticky", top: 0, zIndex: 10,
        background: "rgba(8,8,15,0.95)", backdropFilter: "blur(10px)",
        borderBottom: "1px solid rgba(168,85,247,0.12)",
        padding: "14px 20px",
        display: "flex", alignItems: "center", gap: 12,
      }}>
        <a href="/" style={{
          display: "flex", alignItems: "center", justifyContent: "center",
          width: 32, height: 32, borderRadius: 8,
          background: "rgba(255,255,255,0.04)",
          border: "1px solid rgba(255,255,255,0.08)",
          color: "#64748b", fontSize: 14, textDecoration: "none",
        }}>←</a>
        <div>
          <div style={{ fontSize: 13, fontWeight: "bold", color: "#a855f7", letterSpacing: "0.06em" }}>
            Terms of Use
          </div>
          <div style={{ fontSize: 9, color: "#475569", letterSpacing: "0.12em", textTransform: "uppercase", marginTop: 1 }}>
            NAVI by Springer Industries
          </div>
        </div>
      </div>

      <div style={{ maxWidth: 600, margin: "0 auto", padding: "28px 20px" }}>

        <p style={{ fontSize: 10, color: "#475569", marginBottom: 24, lineHeight: 1.6, letterSpacing: "0.04em" }}>
          Last updated: April 2025
        </p>

        <Section title="Agreement">
          By using NAVI, you agree to these Terms of Use. If you do not agree, please
          do not use the application. These terms may be updated from time to time.
          Continued use after changes means you accept the new terms.
        </Section>

        <Section title="What NAVI Is">
          NAVI is an AI-powered assistant designed to provide guidance, education, and
          support across a variety of life topics. NAVI is a tool to help you think
          through situations — it is not a licensed attorney, financial advisor, doctor,
          or certified counselor.
        </Section>

        <Section title="Information Is for Guidance Only">
          All responses from NAVI are generated by artificial intelligence and are
          provided for informational and educational purposes only. NAVI&apos;s responses
          should not be treated as professional legal, financial, medical, or psychological
          advice. Always verify important information with a qualified professional.
        </Section>

        <Section title="Your Responsibility">
          You are solely responsible for the decisions you make based on information
          provided by NAVI. Springer Industries is not liable for any outcomes,
          damages, or losses resulting from your use of this application or reliance
          on its responses.
        </Section>

        <Section title="No Guarantees">
          We do not guarantee that NAVI&apos;s responses will be accurate, complete, or
          up to date. AI systems can make mistakes. Use your own judgment when acting
          on information provided by NAVI.
        </Section>

        <Section title="Voice Feature">
          By activating the voice feature, you consent to your audio being captured
          and processed to provide voice-based responses. This feature is optional and
          requires your explicit permission through your device&apos;s browser settings.
        </Section>

        <Section title="Subscription (NAVI PRO)">
          NAVI PRO is a paid subscription at $50 per month, billed on a recurring
          basis. You may cancel at any time. Cancellation takes effect at the end of
          the current billing period. Refunds are not provided for partial months.
          All payments are processed by Stripe.
        </Section>

        <Section title="Acceptable Use">
          You agree not to use NAVI for any unlawful purpose, to harass others, to
          attempt to extract harmful content, or to circumvent any security features.
          We reserve the right to discontinue service at any time.
        </Section>

        <Section title="Intellectual Property">
          NAVI and all associated content are owned by Springer Industries. You may
          not copy, modify, distribute, or reverse-engineer any part of the application
          without written permission.
        </Section>

        <Section title="Contact">
          For questions about these terms: legal@springerindustries.com
        </Section>

        <div style={{ marginTop: 32, display: "flex", gap: 16 }}>
          <a href="/privacy" style={{
            fontSize: 10, fontFamily: "monospace", color: "#475569",
            textDecoration: "underline", letterSpacing: "0.04em",
          }}>Privacy Policy →</a>
        </div>

      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 24 }}>
      <div style={{
        fontSize: 10, fontFamily: "monospace", fontWeight: "bold",
        color: "#a855f7", letterSpacing: "0.18em", textTransform: "uppercase",
        marginBottom: 8,
      }}>
        {title}
      </div>
      <p style={{
        fontSize: 12, fontFamily: "monospace", color: "#94a3b8",
        lineHeight: 1.75, margin: 0,
      }}>
        {children}
      </p>
    </div>
  );
}
